In [7]:
str_concat = s + s_2
print(str_concat)

HackerRank is the best place to learn and practice coding!

In [1]:
import pandas as pd
pd.__version__

'0.23.4'

In [2]:
#Read the CSV File into df
df = pd.read_csv('../data/movies_metadata.csv', low_memory=False)

#We will find out what the following code does a little later!
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
#Output the type of df
type(df)

pandas.core.frame.DataFrame

In [5]:
#Output the shape of df
df.shape

(45466, 24)

In [6]:
!pip install pandas_profiling

Collecting pandas_profiling
  Downloading https://files.pythonhosted.org/packages/a7/7c/84f15ee705793a3cdd43bc65e6166d65d36f743b815ea517b02582989533/pandas_profiling-1.4.1-py2.py3-none-any.whl
Requirement already satisfied: pandas>=0.19 in c:\programdata\anaconda3\lib\site-packages (from pandas_profiling) (0.23.4)
Requirement already satisfied: six>=1.9 in c:\programdata\anaconda3\lib\site-packages (from pandas_profiling) (1.12.0)
Requirement already satisfied: matplotlib>=1.4 in c:\programdata\anaconda3\lib\site-packages (from pandas_profiling) (3.0.2)
Requirement already satisfied: jinja2>=2.8 in c:\programdata\anaconda3\lib\site-packages (from pandas_profiling) (2.10)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.19->pandas_profiling) (2.7.5)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.19->pandas_profiling) (2018.7)
Requirement already satisfied: numpy>=1.9.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.19->pandas_profiling) (1.15.4)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=1.4->pandas_profiling) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=1.4->pandas_profiling) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=1.4->pandas_profiling) (2.3.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=2.8->pandas_profiling) (1.1.0)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=1.4->pandas_profiling) (40.6.3)
Installing collected packages: pandas-profiling
Successfully installed pandas-profiling-1.4.1

In [10]:
from pandas_profiling import ProfileReport

In [11]:
ProfileReport(df)

In [12]:
#Output the columns of df
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [16]:
#Select the second movie in df
second = df.iloc[1]
second

adult                                                                False
belongs_to_collection                                                  NaN
budget                                                            65000000
genres                   [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
homepage                                                               NaN
id                                                                    8844
imdb_id                                                          tt0113497
original_language                                                       en
original_title                                                     Jumanji
overview                 When siblings Judy and Peter discover an encha...
popularity                                                       17.015539
poster_path                               /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
production_companies     [{'name': 'TriStar Pictures', 'id': 559}, {'na...
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    1995-12-15
revenue                                                        2.62797e+08
runtime                                                                104
spoken_languages         [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
status                                                            Released
tagline                          Roll the dice and unleash the excitement!
title                                                              Jumanji
video                                                                False
vote_average                                                           6.9
vote_count                                                            2413
Name: 1, dtype: object

In [ ]:
from pandas.io.json import json_normalize

json_normalize(data = df['genres'], record_path=['genres'])

In [34]:
#Change the index to the title
df = df.set_index('title')

#Access the movie with title 'Jumanji'
jum = df.loc['Jumanji']
jum

adult                                                                False
belongs_to_collection                                                  NaN
budget                                                            65000000
genres                   [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
homepage                                                               NaN
id                                                                    8844
imdb_id                                                          tt0113497
original_language                                                       en
original_title                                                     Jumanji
overview                 When siblings Judy and Peter discover an encha...
popularity                                                       17.015539
poster_path                               /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
production_companies     [{'name': 'TriStar Pictures', 'id': 559}, {'na...
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    1995-12-15
revenue                                                        2.62797e+08
runtime                                                                104
spoken_languages         [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
status                                                            Released
tagline                          Roll the dice and unleash the excitement!
video                                                                False
vote_average                                                           6.9
vote_count                                                            2413
Name: Jumanji, dtype: object

In [35]:
df = df.reset_index()

In [36]:
#Create a smaller dataframe with a subset of all features
small_df = df[['title', 'release_date', 'budget', 'revenue', 'runtime', 'genres']]

#Output only the first 5 rows of small_df
small_df.head()

,title,release_date,budget,revenue,runtime,genres
0,Toy Story,1995-10-30,30000000,373554033.0,81.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '..."
1,Jumanji,1995-12-15,65000000,262797249.0,104.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."
2,Grumpier Old Men,1995-12-22,0,0.0,101.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ..."
3,Waiting to Exhale,1995-12-22,16000000,81452156.0,127.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
4,Father of the Bride Part II,1995-02-10,0,76578911.0,106.0,"[{'id': 35, 'name': 'Comedy'}]"

In [37]:
#Get information of the data types of each feature
small_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 6 columns):
title           45460 non-null object
release_date    45379 non-null object
budget          45466 non-null object
revenue         45460 non-null float64
runtime         45203 non-null float64
genres          45466 non-null object
dtypes: float64(2), object(4)
memory usage: 2.1+ MB

In [38]:
df['budget'].astype('float')

ValueError: could not convert string to float: '/ff9qCepilowshEtG2GYWwzt2bs4.jpg'

In [42]:
#Import the numpy library 
import numpy as np

#Function to convert to float manually
def to_float(x):
    try:
        x = float(x)
    except: 
        x = np.nan
    return x

#Apply the to_float function to all values in the budget column
small_df['budget'] = small_df['budget'].apply(to_float)

#Try converting to float using pandas astype
small_df['budget'] = small_df['budget'].astype('float')

#Get the data types for all features
small_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 6 columns):
title           45460 non-null object
release_date    45379 non-null object
budget          45463 non-null float64
revenue         45460 non-null float64
runtime         45203 non-null float64
genres          45466 non-null object
dtypes: float64(3), object(3)
memory usage: 2.1+ MB

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [47]:
small_df['release_date'] = pd.to_datetime(small_df['release_date'] , errors='coerce')
small_df.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,title,release_date,budget,revenue,runtime,genres
0,Toy Story,1995-10-30,30000000.0,373554033.0,81.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '..."
1,Jumanji,1995-12-15,65000000.0,262797249.0,104.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."
2,Grumpier Old Men,1995-12-22,0.0,0.0,101.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ..."
3,Waiting to Exhale,1995-12-22,16000000.0,81452156.0,127.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
4,Father of the Bride Part II,1995-02-10,0.0,76578911.0,106.0,"[{'id': 35, 'name': 'Comedy'}]"

In [53]:
#Convert release_date into pandas datetime format
small_df['release_date'] = pd.to_datetime(small_df['release_date'], errors='coerce')

#Extract year from the datetime
small_df['year'] = small_df['release_date'].apply(lambda x: str(x).split('-')[0] if x != np.nan else np.nan)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [34]:
#Sort DataFrame based on release year
small_df = small_df.sort_values('year')

small_df.head()

,title,release_date,budget,revenue,runtime,genres,year
34940,Passage of Venus,1874-12-09,0.0,0.0,1.0,"[{'id': 99, 'name': 'Documentary'}]",1874
34937,Sallie Gardner at a Gallop,1878-06-14,0.0,0.0,1.0,"[{'id': 99, 'name': 'Documentary'}]",1878
41602,Buffalo Running,1883-11-19,0.0,0.0,1.0,"[{'id': 99, 'name': 'Documentary'}]",1883
34933,Man Walking Around a Corner,1887-08-18,0.0,0.0,1.0,"[{'id': 99, 'name': 'Documentary'}]",1887
34934,Accordion Player,1888-01-01,0.0,0.0,1.0,"[{'id': 99, 'name': 'Documentary'}]",1888

In [55]:
#Sort Movies based on revenue (in descending order)
small_df = small_df.sort_values('revenue', ascending=False)

small_df.head()

,title,release_date,budget,revenue,runtime,genres,year
14551,Avatar,2009-12-10,237000000.0,2.787965e+09,162.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2009
26555,Star Wars: The Force Awakens,2015-12-15,245000000.0,2.068224e+09,136.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2015
1639,Titanic,1997-11-18,200000000.0,1.845034e+09,194.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",1997
17818,The Avengers,2012-04-25,220000000.0,1.519558e+09,143.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",2012
25084,Jurassic World,2015-06-09,150000000.0,1.513529e+09,124.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2015

In [56]:
#Select only those movies which earned more than 1 billion
new = small_df[small_df['revenue'] > 1e9]

new

,title,release_date,budget,revenue,runtime,genres,year
14551,Avatar,2009-12-10,237000000.0,2.787965e+09,162.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2009
26555,Star Wars: The Force Awakens,2015-12-15,245000000.0,2.068224e+09,136.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2015
1639,Titanic,1997-11-18,200000000.0,1.845034e+09,194.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",1997
17818,The Avengers,2012-04-25,220000000.0,1.519558e+09,143.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",2012
25084,Jurassic World,2015-06-09,150000000.0,1.513529e+09,124.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2015
28830,Furious 7,2015-04-01,190000000.0,1.506249e+09,137.0,"[{'id': 28, 'name': 'Action'}]",2015
26558,Avengers: Age of Ultron,2015-04-22,280000000.0,1.405404e+09,141.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2015
17437,Harry Potter and the Deathly Hallows: Part 2,2011-07-07,125000000.0,1.342000e+09,130.0,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",2011
22110,Frozen,2013-11-27,150000000.0,1.274219e+09,102.0,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",2013
42222,Beauty and the Beast,2017-03-16,160000000.0,1.262886e+09,129.0,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",2017
43255,The Fate of the Furious,2017-04-12,250000000.0,1.238765e+09,136.0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",2017
20830,Iron Man 3,2013-04-18,200000000.0,1.215440e+09,130.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2013
30700,Minions,2015-06-17,74000000.0,1.156731e+09,91.0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",2015
26567,Captain America: Civil War,2016-04-27,250000000.0,1.153304e+09,147.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",2016
17293,Transformers: Dark of the Moon,2011-06-28,195000000.0,1.123747e+09,154.0,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",2011
7000,The Lord of the Rings: The Return of the King,2003-12-01,94000000.0,1.118889e+09,201.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",2003
19261,Skyfall,2012-10-25,200000000.0,1.108561e+09,143.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2012
23617,Transformers: Age of Extinction,2014-06-25,210000000.0,1.091405e+09,165.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",2014
18252,The Dark Knight Rises,2012-07-16,250000000.0,1.084939e+09,165.0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",2012
15348,Toy Story 3,2010-06-16,200000000.0,1.066970e+09,103.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",2010
11008,Pirates of the Caribbean: Dead Man's Chest,2006-06-20,200000000.0,1.065660e+09,151.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",2006
41489,Rogue One: A Star Wars Story,2016-12-14,200000000.0,1.056057e+09,133.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2016
17124,Pirates of the Caribbean: On Stranger Tides,2011-05-14,380000000.0,1.045714e+09,136.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",2011
38176,Finding Dory,2016-06-16,200000000.0,1.028571e+09,97.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",2016
14892,Alice in Wonderland,2010-03-03,200000000.0,1.025491e+09,108.0,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",2010
36253,Zootopia,2016-02-11,150000000.0,1.023784e+09,108.0,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",2016
19971,The Hobbit: An Unexpected Journey,2012-11-26,250000000.0,1.021104e+09,169.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",2012
44009,Despicable Me 3,2017-06-15,80000000.0,1.020063e+09,96.0,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",2017
12481,The Dark Knight,2008-07-16,185000000.0,1.004558e+09,152.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",2008

In [57]:
#Select only those movies which earned more than 1 billion and spent less than 150 million

new2 = small_df[(small_df['revenue'] > 1e9) & (small_df['budget'] < 1.5e8)]
new2

,title,release_date,budget,revenue,runtime,genres,year
17437,Harry Potter and the Deathly Hallows: Part 2,2011-07-07,125000000.0,1.342000e+09,130.0,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",2011
30700,Minions,2015-06-17,74000000.0,1.156731e+09,91.0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",2015
7000,The Lord of the Rings: The Return of the King,2003-12-01,94000000.0,1.118889e+09,201.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",2003
44009,Despicable Me 3,2017-06-15,80000000.0,1.020063e+09,96.0,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",2017

In [58]:
type(small_df['year'])

pandas.core.series.Series

In [59]:

#Get the runtime Series object
runtime = small_df['runtime']

#Print the longest runtime of any movie
print(runtime.max())

#Print the shortest runtime of any movie
print(runtime.min())

1256.0
0.0

In [60]:
#Get the budget Series object
budget = small_df['budget']

#Print the mean budget of the movies
print(budget.mean())

#Print the median budget of the movies
print(budget.median())

4224578.813474693
0.0

In [61]:
#Get the revenue Series object
revenue = small_df['revenue']

#Revenue generated by the 90th percentile movie
revenue.quantile(0.90)

8267610.399999982

In [62]:
#Get number of movies released each year
small_df['year'].value_counts()

2014    1974
2015    1905
2013    1889
2012    1722
2011    1667
2016    1604
2009    1586
2010    1501
2008    1473
2007    1320
2006    1270
2005    1125
2004     992
2002     905
2003     882
2001     865
2000     789
1999     723
1998     722
1997     661
1996     633
1995     599
1994     544
2017     532
1993     489
1988     467
1987     462
1992     453
1989     439
1990     427
        ...
1900      14
1896      14
1912      14
1898      13
1894      13
1913      13
1909      10
1901      10
1904       8
1897       8
1907       7
1910       7
1895       7
1906       7
1891       6
1908       6
1911       6
2018       5
1899       5
1905       5
1890       5
1892       3
1902       2
1888       2
1893       1
1883       1
1874       1
2020       1
1878       1
1887       1
Name: year, Length: 136, dtype: int64